### ISSUE TITLE
Release 1.0.0 ?

### ISSUE THREAD

**Issue by abuiles** [quaertym/ember-cli-dependency-checker#32]
Hey, could you please release so the following goes out https://github.com/quaertym/ember-cli-dependency-checker/pull/31  ? we would like to include this in the next release of ember-cli which will be out today (hopefully)

**Comment by mixonic** [comment]
@quaertym the peanut gallery of Ember-CLI encourages you to go 1.0.0. Then we can just float the dependency instead of needing to pin to a specific version. There would be less of a crush to get releases out in sync.

@rwjblue has promised me that you will not run out of version numbers :-) And I definitely think this is 1.0 ready.

**Comment by quaertym** [comment]
I will release this in about 4 hours. I am currently making some changes.

**Comment by quaertym** [comment]
Fixed by https://github.com/quaertym/ember-cli-dependency-checker/releases/tag/v1.0.0

**Comment by mixonic** [comment]
@quaertym Thanks so much! I read your latest commits, they look good :-)

**Comment by quaertym** [comment]
@mixonic Thanks, I guess it is ready before the new ember-cli release:
https://github.com/ember-cli/ember-cli/pull/4058
